name: gfdemo
channels:
  - conda-forge
dependencies:
  - python=3.11
  - numpy
  - gdstk
  - jupyterlab
  - pip
  - pip:
    - gdsfactory==7.26.1
    - nbstripout
    - cspdk==0.8.1
    # - sky130==0.11.0